export enum LLMTypeEnum {
  EMBEDDING = 'embedding',
  CHAT = 'chat',
  RERANK = 'rerank',
  SPEECH2TEXT = 'speech2text',
  IMAGE2TEXT = 'image2text',
  TTS = 'tts'
}

export const enum LLMProvider {
  TONGYI = 'Tongyi-Qianwen',
  MOONSHOT = 'Moonshot',
  OPENAI = 'OpenAI',
  ZHIPU = 'ZHIPU-AI',
  WENXIN = '文心一言',
  OLLAMA = 'Ollama',
  XINFERENCE = 'Xinference',
  DEEPSEEK = 'DeepSeek',
  VOLC_ENGINE = 'VolcEngine',
  BAICHUAN = 'BaiChuan',
  JINA = 'Jina',
  MINIMAX = 'MiniMax',
  MISTRAL = 'Mistral',
  AZURE_OPENAI = 'Azure-OpenAI',
  BEDROCK = 'Bedrock',
  GEMINI = 'Gemini',
  GROQ = 'Groq',
  OPENROUTER = 'OpenRouter',
  LOCALAI = 'LocalAI',
  STEPFUN = 'StepFun',
  NVIDIA = 'NVIDIA',
  LM_STUDIO = 'LM-Studio',
  OPENAI_API_COMPATIBLE = 'OpenAI-API-Compatible',
  COHERE = 'cohere',
  LEPTON_AI = 'LeptonAI',
  TOGETHER_AI = 'TogetherAI',
  PERFX_CLOUD = 'PerfXCloud',
  UPSTAGE = 'Upstage',
  NOVITA_AI = 'novita.ai',
  SILICONFLOW = 'SILICONFLOW',
  PPIO = 'PPIO',
  YI = '01.AI',
  REPLICATE = 'Replicate',
  HUNYUAN = 'Tencent Hunyuan',
  SPARK = 'XunFei Spark',
  YIYAN = 'BaiduYiyan',
  FISH_AUDIO = 'Fish Audio',
  TENCENT_CLOUD = 'Tencent Cloud',
  ANTHROPIC = 'Anthropic',
  VOYAGE = 'Voyage AI',
  GOOGLE_CLOUD = 'Google Cloud',
  HUGGINGFACE = 'HuggingFace',
  YOUDAO = 'Youdao',
  BAAI = 'BAAI',
  NOMIC_AI = 'nomic-ai',
  JINAAI = 'jinaai',
  SENTENCE_TRANSFORMERS = 'sentence-transformers',
  GPUSTACK = 'GPUStack'
}

export const IconMap: Record<LLMProvider, string> = {
  [LLMProvider.TONGYI]: 'tongyi',
  [LLMProvider.MOONSHOT]: 'moonshot',
  [LLMProvider.OPENAI]: 'openai',
  [LLMProvider.ZHIPU]: 'zhipu',
  [LLMProvider.WENXIN]: 'wenxin',
  [LLMProvider.OLLAMA]: 'ollama',
  [LLMProvider.XINFERENCE]: 'xinference',
  [LLMProvider.DEEPSEEK]: 'deepseek',
  [LLMProvider.VOLC_ENGINE]: 'volc_engine',
  [LLMProvider.BAICHUAN]: 'baichuan',
  [LLMProvider.JINA]: 'jina',
  [LLMProvider.MINIMAX]: 'chat-minimax',
  [LLMProvider.MISTRAL]: 'mistral',
  [LLMProvider.AZURE_OPENAI]: 'azure',
  [LLMProvider.BEDROCK]: 'bedrock',
  [LLMProvider.GEMINI]: 'gemini',
  [LLMProvider.GROQ]: 'groq-next',
  [LLMProvider.OPENROUTER]: 'open-router',
  [LLMProvider.LOCALAI]: 'local-ai',
  [LLMProvider.STEPFUN]: 'stepfun',
  [LLMProvider.NVIDIA]: 'nvidia',
  [LLMProvider.LM_STUDIO]: 'lm-studio',
  [LLMProvider.OPENAI_API_COMPATIBLE]: 'openai-api',
  [LLMProvider.COHERE]: 'cohere',
  [LLMProvider.LEPTON_AI]: 'lepton-ai',
  [LLMProvider.TOGETHER_AI]: 'together-ai',
  [LLMProvider.PERFX_CLOUD]: 'perfx-cloud',
  [LLMProvider.UPSTAGE]: 'upstage',
  [LLMProvider.NOVITA_AI]: 'novita-ai',
  [LLMProvider.SILICONFLOW]: 'siliconflow',
  [LLMProvider.PPIO]: 'ppio',
  [LLMProvider.YI]: 'yi',
  [LLMProvider.REPLICATE]: 'replicate',
  [LLMProvider.HUNYUAN]: 'hunyuan',
  [LLMProvider.SPARK]: 'spark',
  [LLMProvider.YIYAN]: 'yiyan',
  [LLMProvider.FISH_AUDIO]: 'fish-audio',
  [LLMProvider.TENCENT_CLOUD]: 'tencent-cloud',
  [LLMProvider.ANTHROPIC]: 'anthropic',
  [LLMProvider.VOYAGE]: 'voyage',
  [LLMProvider.GOOGLE_CLOUD]: 'google-cloud',
  [LLMProvider.HUGGINGFACE]: 'huggingface',
  [LLMProvider.YOUDAO]: 'youdao',
  [LLMProvider.BAAI]: 'baai',
  [LLMProvider.NOMIC_AI]: 'nomic-ai',
  [LLMProvider.JINAAI]: 'jina',
  [LLMProvider.SENTENCE_TRANSFORMERS]: 'sentence-transformers',
  [LLMProvider.GPUSTACK]: 'gpustack'
};

export const LocalLlmFactories = [
  'Ollama',
  'Xinference',
  'LocalAI',
  'LM-Studio',
  'OpenAI-API-Compatible',
  'TogetherAI',
  'Replicate',
  'OpenRouter',
  'HuggingFace',
  'GPUStack'
];
